! Winteracter resource identifiers. Created : 13/Apr/2014 12:50:18
!
! This file is generated by the Winteracter resource editor.
! It should not be edited manually. It is also not advisable to load this
! file in a text editor, while working on the associated resource file,
! since this may prevent the resource identifiers file from being updated.
! To view the names and values of resource identifiers, use the
! "Identifier Names and Values" or "Used Identifiers" options on the
! resource editor's "View" menu. Both dialogs also include a "Copy id"
! button which allows identifier names to be copied via the clipboard.
! Opening this file in an editor should therefore not be necessary.
!
      MODULE RESID
      IMPLICIT NONE
! Silence picky compilers (e.g. Open64 complains about no public objects)
      INTEGER, PARAMETER :: ID_NO_IDENTIFIERS_DEFINED = 0
      END MODULE RESID
